CREATE DATABASE iotdata;
CREATE RETENTION POLICY raw_90d ON iotdata DURATION 90d REPLICATION 1 DEFAULT;
CREATE RETENTION POLICY avg_1y ON iotdata DURATION 365d REPLICATION 1;
CREATE CONTINUOUS QUERY cq_downsample_5m ON iotdata
BEGIN
  SELECT mean(*) INTO iotdata."avg_1y".downsampled_5m
  FROM iot_raw GROUP BY time(5m)
END;
